#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Autonomous Futures Trading Bot

set -e

echo "========================================"
echo "Autonomous Futures Trading Bot Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Project root
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${BLUE}Project root: $PROJECT_ROOT${NC}"

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Python version
PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d'.' -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d'.' -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 10 ]); then
    echo -e "${RED}Error: Python 3.10+ required. Found: $PYTHON_VERSION${NC}"
    exit 1
fi
echo -e "${GREEN}Python version: $PYTHON_VERSION${NC}"

# Check if TWS is running (optional check)
if nc -z localhost 7497 2>/dev/null; then
    echo -e "${GREEN}IB TWS detected on port 7497${NC}"
else
    echo -e "${YELLOW}Warning: IB TWS not detected on port 7497${NC}"
    echo -e "${YELLOW}Make sure TWS/Gateway is running with API enabled before starting the bot${NC}"
fi

# ============================================
# VIRTUAL ENVIRONMENT SETUP
# ============================================

echo ""
echo "Setting up Python environment..."

# Create virtual environment if it doesn't exist
if [ ! -d ".venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv .venv
    echo -e "${GREEN}Virtual environment created${NC}"
else
    echo -e "${GREEN}Virtual environment exists${NC}"
fi

# Activate virtual environment
source .venv/bin/activate
echo -e "${GREEN}Virtual environment activated${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

if [ -f "requirements.txt" ]; then
    pip install --upgrade pip
    pip install -r requirements.txt
    echo -e "${GREEN}Dependencies installed${NC}"
else
    echo -e "${YELLOW}Warning: requirements.txt not found. Creating basic dependencies...${NC}"
    pip install --upgrade pip
    pip install ib_async>=2.1.0 river>=0.23.0 dash>=3.3.0 plotly>=5.18.0 pandas>=2.0.0 pandas_market_calendars>=5.2.4 numpy>=1.26.0 aiohttp>=3.9.0 dash-bootstrap-components>=1.5.0
    pip install pytest>=7.0.0 pytest-asyncio>=0.21.0 black ruff
    echo -e "${GREEN}Core dependencies installed${NC}"
fi

# ============================================
# CREATE DIRECTORY STRUCTURE
# ============================================

echo ""
echo "Ensuring directory structure..."

mkdir -p src/core
mkdir -p src/data
mkdir -p src/trading
mkdir -p src/learning
mkdir -p src/dashboard
mkdir -p tests/integration

# Create __init__.py files if they don't exist
for dir in src src/core src/data src/trading src/learning src/dashboard tests tests/integration; do
    if [ ! -f "$dir/__init__.py" ]; then
        touch "$dir/__init__.py"
        echo "Created $dir/__init__.py"
    fi
done

echo -e "${GREEN}Directory structure ready${NC}"

# ============================================
# ENVIRONMENT VARIABLES
# ============================================

echo ""
echo "Environment configuration:"
echo "  IB_HOST:       ${IB_HOST:-127.0.0.1} (default: 127.0.0.1)"
echo "  IB_PORT:       ${IB_PORT:-7497} (default: 7497)"
echo "  IB_CLIENT_ID:  ${IB_CLIENT_ID:-1} (default: 1)"
echo "  DASHBOARD_PORT: ${DASHBOARD_PORT:-8050} (default: 8050)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Setup Complete!${NC}"
echo "========================================"
echo ""
echo "To start the trading bot:"
echo "  1. Ensure IB TWS/Gateway is running on port 7497"
echo "  2. Activate environment: source .venv/bin/activate"
echo "  3. Run: python src/main.py"
echo ""
echo "To start the dashboard (separate terminal):"
echo "  1. Activate environment: source .venv/bin/activate"
echo "  2. Run: python src/dashboard/app.py"
echo "  3. Open: http://localhost:8050"
echo ""
echo "Service URLs:"
echo "  Dashboard: http://localhost:${DASHBOARD_PORT:-8050}"
echo "  TWS API:   localhost:${IB_PORT:-7497} (external)"
echo ""
